vim.g.mapleader = " "

require("options")
require("lsp")
require("theme")
require("netrw")
require("statusline")
require("find-files")
require("find-buffer")
require("grep")
require("restore-last-position")
require("diagnostics")
require("format")
require("wordwrap")
require("overtype").setup({ ")", "]", "}", ">", "'", '"', "`" })
require("keybindings")
require("marks-gutter")
require("close-buffer")
